task :populate_guests => :environment do
names = [
"Eileen and Robert",
"Rebecca",
"Suz",
"John and family",
"Celia and family",
"Angela and family",
"Carol and family",
"Trish and family",
"Jenny and family",
"Susan and family",
"David and Irene",
"Reg and Rona",
"Linda Richardson",
"Joan Miller",
"Katie and Ben",
"Holly and Gemma",
"Laura and Dave",
"Ciara and Mike",
"Becca Dick",
"Sarah Horton",
"Daniel and Amy",
"Will and guest",
"Fiona and guest",
"Lucy and Iain",
"Lucy and Wayne",
"James and Catherine",
"Susanna and Alex",
"Susanne and Neil",
"Andy and Olivia",
"Diego and Lena",
"Eric Chilenu",
"Ben and Natasha",
"Paddy and Rhiannon",
"Sarah 'Trammy' Tramm",
"Felipe 'Rata' Restrepo",
"Ana and Chris",
"Yeyo",
"Alejo and Joy",
"Rodrigo y Pilar",
"Amalia y Pacho",
"Tomás y Naty",
"Daniel 'Duro'Mesa y muchacha",
"Ceci, Susi y Pedro",
"Alejo Ospina y Kelly",
"Camolito mijo y Luisita",
"Bruno y Clara",
"Daniel 'Energizer' Ariza",
"Silvia",
"Calichon y Sandra",
"Lucas Lopera y familia",
"Alan Bradbury",
"Andy 'Peeky' and Partner",
"Rob",
"Elisa and Dave",
"Ona",
"Joe and Jen"]

names.each{|n| Guest.create!(name: n)}
end
